language: node_js
node_js:
  - '9'
  - '10'
  - '11'
  - '12'
notifications:
  email: markusgilg@outlook.de
jobs:
  include:
    - stage: build
      script: npm run build
    - stage: test
      script: npm run coverage
